// this is the gloabl layout of the page here hum jo bhi dnege vok apake sare pages par render ho jayege 
import { Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// this page ka content aapke sare pages me common hoga so this will hav the same for all the pages 

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Root Layout</h1>
        {/* <Navbar /> */}
        {children}
        </body>
    </html>
  );
}

// the root layout willl be on the every page of the website so it is the global layout of the website
